name: CD - Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["CI - Build & Push to GAR"]
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Download Image Tag Artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact

    - name: Deploy to Cloud Run
      run: |
        IMAGE_NAME=$(cat image-tag.txt)
        gcloud run deploy ${{ secrets.CLOUDRUN_SERVICE }} \
          --image=$IMAGE_NAME \
          --region=${{ secrets.REGION }} \
          --platform=managed \
          --allow-unauthenticated
