name: CI - Build, Dockerize & Push to GAR

on:
  push:
    branches:
      - master  # Runs when changes are pushed to 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build the Java Application
      run: mvn clean package

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Configure Docker to use gcloud CLI
      run: |
        gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

    - name: Build and Tag Docker Image
      run: |
        IMAGE_NAME=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/uc-ai-dev/app
        docker build -t $IMAGE_NAME:latest .

    - name: Push Docker Image to GAR
      run: |
        IMAGE_NAME=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/uc-ai-dev/app
        docker push $IMAGE_NAME:latest

